name: docs
channels:
  - conda-forge
  - epoc-project
dependencies:
  - python
  - doxygen
  - sphinx=7.1.2
  - breathe
  - furo
  - epoc
  - simple_tem
  - pip:
    - jfjoch_client #currently not available on conda-forge
  
